
import { useState } from "react"
import Head from "next/head"

import styles from '../styles/Home.module.css'

export default function Home() {
  const [ name, setName ] = useState("")
  const [ email, setEmail ] = useState("")
  const [ subject, setSubject ] = useState("")
  const [ message, setMessage ] = useState("")
  const [ formError, setFormError ] = useState("")
  const [ formSuccess, setFormSuccess ] = useState("")

  async function handleSubmit(e) {
    e.preventDefault()

    if (!name) {
      setFormError("Missing field \"name\".")
      setTimeout(() => {
        setFormError("")
      }, 3000)
      return
    } else if (!email) {
      setFormError("Missing field \"email\".")
      setTimeout(() => {
        setFormError("")
      }, 3000)
      return
    } else if (!subject) {
      setFormError("Missing field \"subject\".")
      setTimeout(() => {
        setFormError("")
      }, 3000)
      return
    } else if (!message) {
      setFormError("Missing field \"message\".")
      setTimeout(() => {
        setFormError("")
      }, 3000)
      return
    } else {
      const res = await fetch(`${ process.env.NEXT_PUBLIC_BASE_URL }/api/nodemailer`, {
        method: "POST",
        mode: "no-cors",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({ name, email, subject, message })
      })
  
      const data = await res.json()

      if (data.success) {
        setName("")
        setEmail("")
        setSubject("")
        setMessage("")
        setFormError("")
        setFormSuccess("Successful submission!")
        setTimeout(() => {
          setFormSuccess("")
        }, 3000)
      }
    }
  }

  return (
    <>
      <Head>
        <title>nodemailerdemo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={ styles.nodemailer }>
        <form onSubmit={ (e) => handleSubmit(e) }>
          <section>
            <h1>Send yourself an email!</h1>
          </section>
          <section>
            <label>Name</label>
            <input type="text" value={ name } placeholder="John Doe" onChange={ (e) => setName(e.target.value) } />
          </section>
          <section>
            <label>Email</label>
            <input type="email" value={ email } placeholder="user@email.com" onChange={ (e) => setEmail(e.target.value) } />
          </section>
          <section>
            <label>Subject</label>
            <input type="text" value={ subject } placeholder="Lorem ipsum..." onChange={ (e) => setSubject(e.target.value) } />
          </section>
          <section>
            <label>Message</label>
            <textarea value={ message } placeholder="Lorem ipsum dolor sit amet..." onChange={ (e) => setMessage(e.target.value) } />
          </section>
          <section>
            <label style={{ color: "red" }}>
              { formError.length > 0 ? formError : <></> }
            </label>
            <label style={{ color: "green" }}>
              { formSuccess.length > 0 ? formSuccess : <></> }
            </label>
          </section>
          <section>
            <button>Send message</button>
          </section>
        </form>
      </main>
    </>
  )
}
